name: PR

on:
  pull_request:
    paths-ignore:
      - 'ci/**'
      - '**/*.md'

env:
  IMAGE_NAME: docker-ecr-ap-training-image

jobs:
  snyk-monitor-mgt-dev:
    runs-on: ubuntu-latest
    needs: publish-docker
    steps:
      - uses: actions/checkout@v2
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.DEV_ECR_AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.DEV_ECR_AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.DEV_ECR_AWS_SESSION_TOKEN }}
          aws-region: eu-west-2
      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1
      - name: Pull image from Amazon ECR
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: ${{ env.IMAGE_NAME }}
          IMAGE_TAG: latest
        run: |
          docker pull -q $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
      - name: Run Snyk monitoring
        uses: snyk/actions/docker@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          command: monitor
          image: ${{ steps.login-ecr.outputs.registry }}/${{ env.IMAGE_NAME }}:latest
          args: --file=./build/Dockerfile --policy-path=./build/.snyk --org=dwp-dataworks
  docker-build-and-scan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build Docker image
        run:
          docker build -t ${{ env.IMAGE_NAME }}:latest . || echo "Build Failed"
        working-directory: build
  docker-publish-dev:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Build Docker Image
        env:
          DEV_AWS_ACCESS_KEY_ID: ${{ secrets.DEV_ECR_AWS_ACCESS_KEY_ID }}
          DEV_AWS_SECRET_ACCESS_KEY: ${{ secrets.DEV_ECR_AWS_SECRET_ACCESS_KEY}}
          DEV_AWS_SESSION_TOKEN: ${{ secrets.DEV_ECR_AWS_SESSION_TOKEN }}
          DEV_AWS_ACCOUNT: ${{ secrets.DEV_ECR_AWS_ACCOUNT }}
          AWS_REGION: eu-west-2
          SEM_VER: "2"
        run:
          export DEV_AWS_ACCESS_KEY_ID DEV_AWS_SECRET_ACCESS_KEY DEV_AWS_SESSION_TOKEN ;
          export AWS_REGION DEV_AWS_ACCOUNT ;
          chmod 777 ./build-dev.sh ;
          ./build-dev.sh
        working-directory: build
  format:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Set up Python 3.8
        uses: actions/setup-python@v1
        with:
          python-version: 3.8

      - name: Install Black
        run: pip install black

      - name: Run black --check .
        id: check-formatting
        run: black --check .
        continue-on-error: true

      - name: If needed, commit black changes to the pull request
        if: ${{ steps.check-formatting.outcome == 'failure' }}
        run: |
          black .
          git config --global user.name ${{ secrets.CI_GITHUB_USERNAME }}
          git config --global user.email ${{ secrets.CI_GITHUB_EMAIL }}
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/$GITHUB_REPOSITORY
          git checkout $GITHUB_HEAD_REF
          git commit -am "Fixup: Format Python code with Black"
          git push
